/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controllers.MovimentacaoController;
import controllers.TipoDeDespesasController;
import controllers.VeiculoController;
import javax.swing.JOptionPane;
import modelos.classes.Movimentacao;
import modelos.classes.TipoDeDespesa;
import modelos.classes.Veiculo;
import relatorios.PdfGerador;

/**
 *
 * @author narut
 */
public class TelaDeRelatorios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaDeRelatorios.class.getName());

    /**
     * Creates new form TelaDeRelatorios
     */
    public TelaDeRelatorios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButtonRelatorioConfirmar = new javax.swing.JButton();
        jButtonRelatorioControle = new javax.swing.JButton();
        jButtonRelatorioMov = new javax.swing.JButton();
        jButtonRelatorioDespesas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 146, 126));

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(16, 58, 83));

        jButton1.setBackground(new java.awt.Color(16, 58, 83));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/botao-voltar.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonRelatorioConfirmar.setText("Confirmar");
        jButtonRelatorioConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioConfirmarActionPerformed(evt);
            }
        });

        jButtonRelatorioControle.setText("Gerar Relatorio Controle");
        jButtonRelatorioControle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioControleActionPerformed(evt);
            }
        });

        jButtonRelatorioMov.setText("Gerar Relatorio Movimentação");
        jButtonRelatorioMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioMovActionPerformed(evt);
            }
        });

        jButtonRelatorioDespesas.setText("Gerar Relatorio Despesas");
        jButtonRelatorioDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioDespesasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(844, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButtonRelatorioControle, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonRelatorioMov, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(jButtonRelatorioDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(jButtonRelatorioConfirmar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRelatorioControle, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorioMov, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRelatorioDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(jButtonRelatorioConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        jLabel2.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        jLabel2.setText("GYNLOG");

        jLabel4.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel4.setText("Controle de Frotas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(38, 38, 38))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(25, 25, 25))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TelaPrincipal TelaDeRelatorio = new TelaPrincipal();
        TelaDeRelatorio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonRelatorioConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioConfirmarActionPerformed
        List<String> linhas = new ArrayList<>();

    linhas.add("=== Veículos ===");
    for (Veiculo v : VeiculoController.getInstance().listarVeiculos()) {
        linhas.add(v.toString());
    }

    linhas.add("\n=== Movimentações ===");
    for (Movimentacao m : MovimentacaoController.getInstance().listarMovimentacoes()) {
        linhas.add(m.toString());
    }

    linhas.add("\n=== Tipos de Despesas ===");
    for (TipoDeDespesa t : TipoDeDespesasController.getInstance().listarTipoDespesas()) {
        linhas.add(t.toString());
    }

    PdfGerador.gerarRelatorio(
        "Relatório Geral",
        linhas,
        "relatorio_geral.pdf"
    );

    JOptionPane.showMessageDialog(this, "Relatório geral gerado: relatorio_geral.pdf");
    }//GEN-LAST:event_jButtonRelatorioConfirmarActionPerformed

    private void jButtonRelatorioControleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioControleActionPerformed
    List<Veiculo> lista = VeiculoController.getInstance().listarVeiculos();

    // formtacao padrao para o pdf
    List<String> linhas = new ArrayList<>();
    for (Veiculo v : lista) {
        linhas.add(
            "ID: " + v.getIdVeiculo() +
            " | Placa: " + v.getPlaca() +
            " | Marca: " + v.getMarca() +
            " | Modelo: " + v.getModelo() +
            " | Ano: " + v.getAnoFabricacao() +
            " | Status: " + (v.isAtivo() ? "Ativo" : "Inativo")
        );
    }

    // gerando pdf 
    PdfGerador.gerarRelatorio(
        "Relatório de Veículos",
        linhas,
        "rel_veiculos.pdf"
    );

    JOptionPane.showMessageDialog(this, "Relatório gerado: relatorio_veiculos.pdf");
}    
    }//GEN-LAST:event_jButtonRelatorioControleActionPerformed

    private void jButtonRelatorioMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioMovActionPerformed
    List<Movimentacao> lista = MovimentacaoController.getInstance().listarMovimentacoes();

    List<String> linhas = new ArrayList<>();

    for (Movimentacao m : lista) {
        linhas.add(
            "ID Mov: " + m.getIdMovimentacao() +
            " | Veículo ID: " + m.getIdVeiculo() +
            " | Tipo: " + m.getIdTipoDespesa() +
            " | Desc: " + m.getDescricao() +
            " | Data: " + m.getData() +
            " | Valor: R$ " + m.getValor()
        );
    }

    PdfGerador.gerarRelatorio(
        "Relatório de Movimentações",
        linhas,
        "relatorio_movimentacoes.pdf"
    );

    JOptionPane.showMessageDialog(this, "Relatório gerado: relatorio_movimentacoes.pdf");

    }//GEN-LAST:event_jButtonRelatorioMovActionPerformed

    private void jButtonRelatorioDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioDespesasActionPerformed
    List<TipoDeDespesa> lista = TipoDeDespesasController.getInstance().listarTipoDespesas();

    List<String> linhas = new ArrayList<>();

    for (TipoDeDespesa t : lista) {
        linhas.add(
            "ID Tipo: " + t.getIdTipoDeDespesa() +
            " | Descrição: " + t.getDescricao()
        );
    }

    PdfGerador.gerarRelatorio(
        "Relatório de Tipos de Despesas",
        linhas,
        "relatorio_tipo_despesas.pdf"
    );

    JOptionPane.showMessageDialog(this, "Relatório gerado: relatorio_tipo_despesas.pdf");
    }//GEN-LAST:event_jButtonRelatorioDespesasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaDeRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRelatorioConfirmar;
    private javax.swing.JButton jButtonRelatorioControle;
    private javax.swing.JButton jButtonRelatorioDespesas;
    private javax.swing.JButton jButtonRelatorioMov;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
